### ISSUE TITLE
Datatime and currency formats

### ISSUE THREAD

**Issue by gedw99** [go-playground/universal-translator#15]
Am doing language translation.

It's such a huge area .

If the text to be translated has datatime or currency ( money ) in it what to do ?

I was thinking that the translated text must preserver any datetime and / or currency values in it is some sort of meta description.
That was at runtime when using the translated language you can do a final parse for any of this meta data and also convert datatime and / currency before returning it back to the GUI .

That's my current idea. Any other approaches ?

This lib seems not to support this use case.
But I saw some libs using getText for golang which do support it.

**Comment by joeybloggs** [comment]
@gedw99 are you saying you need to parse text with datetime and money values within it? if so this package is really for building the text from the ground up rather than parsing and manipulating.

perhaps I'm misunderstanding what you mean though, do you have an example?

**Comment by gedw99** [comment]
Hey @joeybloggs 
You got it right.  I need to do i18n but the translations include datetime and currency.
It must be something lots of people hit.
I COULD change thing so they no translated text every has a data time or currency in it.
then i just have to construct a sentence with bits of translated text and datetime and currency formatting at runtime.

thoughts ?

**Comment by joeybloggs** [comment]
Parsing would be very difficult as you would also need to know the source text locale, I personally build the text in bits as you stated.

I have no plans to add that sort of functionality and I know I don't have the free time to. but if you wanted to build something on top of this or even a separate project that would be pretty awesome.

**Comment by gedw99** [comment]
Ah thanks Joey, will follow what you did. Was curious if i was boiling the ocean too much :)
Closing this.
