### ISSUE TITLE
Plural Types do not match CLDR Plural Rules, yields gramatically incorrect for many languages.

### ISSUE THREAD

**Issue by icywolfy** [go-playground/universal-translator#3]
Just a quick view of some of the rules in plurals.go 
It has BN, ES, SW, PT, all as type "2A"
However, they have three different rules...
as I write this, it seems that most of the rules are broken if they are dependent on visible trailing zeros, fractions, or integer-portion rules (that ignore fractional portions)

This ticket is to just bring it to your attention.
Hope you can regenerate the data this in a more automated way

But your code only deals with the pre-2012 plural rules for integer values.  
And is not compatible with CLDR-24 (current CLDR-29) / ICU 52+ (current ICU 57) rules, which take into account that plurals are dependent on absolute value, integer portion, trailing portion, and whether there are displayed trailing zero's or not.  

It doesn't seem there is currently any means to pass in a formatted number, or to provide a Number Formatting rule to be able to even calculate the correct plural form, as the form returned is dependent on the displayed value (with or without trailing zero's for instance)

The English rule is wrong to boot XD
EN: one = (i = 1 and v = 0)
 (  1 book,  1.0 books )
where you have it implemented as one = (n=1)

BN: one =  (n=1 || i=0)
ES: one = (n=1)
AST, CA, SW: one = (n=1 && v=0)
  so, a number formatted as "1" returns ONE, but "1.0" would return OTHER
PT: one = (n=0 || n=1)

THe Croation logic is way off:
HR: 
  one = (v=0 && i%10 = 1 && i%100 != 11) || (f % 10 = 1 && f % 100 != 11)
  few = (v=0 && i % 10 in 2..4 and i % 100 !in 12..14) or ....
  one: 1, 1.1, 2.1
  few: 2, 2.2, 2.3
  other: 1.0 

And can't be merged with Russian which is
  one: = (v=0 and i % 10 = 1 and i % 100 != 11)
  few = (v=0 and i % 10 in 2.4 and i % 100 ! in 2..4)

**Comment by joeybloggs** [comment]
Thank you @icywolfy this is exactly the kind of feedback I need :smile: 

I've been trying to fix this stuff and why I was looking for help with tests that would show these kinds of errors.

I will look into the latest versions of the plural rules and perhaps have to ensure golang.org/x/text/unicode/cldr is parsing the CLDR data correctly.

If I may ask when you say:
```
It doesn't seem there is currently any means to pass in a formatted number, or to provide a Number Formatting rule to be able to even calculate the correct plural form, as the form returned is dependent on the displayed value (with or without trailing zero's for instance)

```

would you be able to provide a short example of what you mean? sudo code would be fine.

Thanks again, I would be grateful for and help or advice you could provide 👍

**Comment by joeybloggs** [comment]
For all interested @icywolfy gave me an idea of how to parse and auto generate the code in a better way that should not only solve the above issue, but make each locale more self contained.

**Comment by icywolfy** [comment]
A default number formatter is required for a number of locales, as the correct plural rule is dependant on **visible** trailing fractional digits, and not absolute value.

In a pseudo-code: 

```php
// Numbers will be formatted as #,###.00
$fractionalFormatter = (new NumberFormatter('en_US'))
  ->setMinimumFractionDigits(2)
  ->setMaximumFractionDigits(2)

// Numbers will be formatted as #,###.## 
$defaultFormatter = new (NumberFormatter('en_US'))

$value = 1
// $defaultFormatter->format($value) == "1"
// $fractionalFormatter->format($value) == "1.00"

$pluralProvider = new PluralProvider('en_US', $defaultFormatter)
$pluralProvider->getRule($value)
// == PLURAL_ONE

$pluralProvider = new PluralProvider('en_US', $fractionalFormatter)
$pluralProvider->getRule($value)
// == PLURAL OTHER

/// or to pass in a formatted number
$pluralProvider = new PluralProvider('en_US')
$pluralProvider->getRule("1.0") // == PLURAL_OTHER
$pluralProvider->getRule("1") // PLURAL_ONE

// Sample Messaging
$message[PLURAL_ONE] = "# gram processed."
$message[PLURAL_OTHER] = "# grams processed."
/*
 Expected results (en_US)
"1 gram processed"
"1.0 grams processed"
*/

// EN Plural Rules are defined currently as

EN[CARDINAL][ONE] = "i = 1 && v = 0" // 1 day
EN[CARDINAL][OTHER] = "" // 2 days, 1.5 days

EN[ORDINAL][ONE] = "n % 10 = 1 && n % 100 != 11" // take the 1st right
EN[ORDINAL][TWO] = "n % 10 = 2 && n % 100 != 12" // take the 2nd right
EN[ORDINAL][FEW] = "n % 10 = 3 && n % 100 != 13" // take the 3rd right
EN[ORDINAL][OTHER] = "" // take the 4th right

EN[RANGE][ONE][OTHER] = PLURAL_OTHER // 1–2 days
EN[RANGE][OTHER][ONE] = PLURAL_OTHER //  0–1 days
EN[RANGE][OTHER][OTHER] = PLURAL_OTHER // 0–2 days

```

And there are three categories of plural rules that need to be addressed, not just ordinals -- if you want to do it properly.

**Comment by joeybloggs** [comment]
Thanks @icywolfy

I'm going to look into generating the equivalent go code right from the the CLDR data

**Comment by joeybloggs** [comment]
hello @icywolfy 

I have split out the locale logic into another repo [locales](https://github.com/go-playground/locales) and believe I've addressed all of the plural rule issues.

I generated these locales from scratch and hope you would be able to take a quick look 😄 

Thanks in Advance!

**Comment by icywolfy** [comment]
I took a quick look, and that locales repo looks well done, and covers some of the use cases I normally come across.  (Not sure about the obscure types yet)  And better yet, gave me some nice ideas as to how to implement some added features in my PHP Library.  +1

**Comment by joeybloggs** [comment]
Awesome, Thank You @icywolfy your time to take a look is very much appreciated 👍
