### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by awp0816** [go-playground/universal-translator#33]
github.com/go-playground/universal-translator.(*translator).Add(0xc000a66cc0, 0x190e280, 0xc0006aff10, 0x1b22580, 0x12, 0x0, 0xc000a66f00, 0xc0006fa288)

**Comment by awp0816** [comment]
github.com/go-playground/universal-translator/translator.go:100

**Comment by VahidYm** [comment]
I have this problem too
When I added swagger to my project

**Comment by deankarn** [comment]
Can you please provide an example?

the only reason I can see for that to error is if you are adding/modifying translations at runtime while its being used.

**Comment by VahidYm** [comment]
In my case, putting Swagger router after translator middleWare causes the error
`
router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
`

**Comment by deankarn** [comment]
Can I get some links or more complete examples? 

I have no idea what code/packages are in play here or how it’s wired together
