### ISSUE TITLE
File format for interchange

### ISSUE THREAD

**Issue by abourget** [go-playground/universal-translator#6]
Sending files for translation to upstream service providers is a common task.  Right now, all my translations are directly in my Go code. I will soon need to send it out.. is there any format in which we could pass all the semantics of `universal-translator`, back and forth ?

This site lists a bunch of them (in which `go-i18n` figures!):

https://phraseapp.com/docs/guides/formats/

Perhaps we can pick one that is used in the industry ?

**Comment by joeybloggs** [comment]
Hello @abourget 

currently, there is no way to export or import a file/file format; it is on my list of features in the README that I would like to do, just haven't found the time; but would love some help with 👍 

I'll have to look at all of them to see if any would work with this library, after a quick glance it looks as if none of them identify if the plural rule is Cardinal, Ordinal or Range before the actual value of One, Two, Few, Many or Other; but haven't looked at all yet.

I'm all for choosing a format that exists and has the data needed 😄

**Comment by joeybloggs** [comment]
Hey @abourget 

I have added a file Import & Export  logic in [release 0.15.0](https://github.com/go-playground/universal-translator/releases/tag/v0.15.0)

I couldn't find a clear and succinct format that I liked that also handled all of my needs and so created my own format, see README.

Having said all that some of the format would have supported my needs, but were just very fragile or confusing for my liking, I would be more than happy to add or accept pull requests for other formats if desired.
